In [44]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [45]:
sales_data = pd.read_csv(r"C:\Users\Administrator\Downloads\sales_data.csv")

In [46]:
sales_data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [47]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [48]:
sales_data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [49]:
sales_data["Country"].value_counts()

Country
United States    9800
Name: count, dtype: int64

In [50]:
sales_data["State"].value_counts()

State
California              1946
New York                1097
Texas                    973
Pennsylvania             582
Washington               504
Illinois                 483
Ohio                     454
Florida                  373
Michigan                 253
North Carolina           247
Virginia                 224
Arizona                  223
Tennessee                183
Colorado                 179
Georgia                  177
Kentucky                 137
Indiana                  135
Massachusetts            135
Oregon                   122
New Jersey               122
Maryland                 105
Wisconsin                105
Delaware                  93
Minnesota                 89
Connecticut               82
Missouri                  66
Oklahoma                  66
Alabama                   61
Arkansas                  60
Rhode Island              55
Mississippi               53
Utah                      53
South Carolina            42
Louisiana                 41
Nevada                    39
Nebraska                  38
New Mexico                37
New Hampshire             27
Iowa                      26
Kansas                    24
Idaho                     21
Montana                   15
South Dakota              12
Vermont                   11
District of Columbia      10
Maine                      8
North Dakota               7
West Virginia              4
Wyoming                    1
Name: count, dtype: int64

In [51]:
total_sales_California = sales_data[sales_data["State"] == "California"]["Sales"].sum()

In [52]:
total_sales_California

446306.4635

In [53]:
total_sales_by_state = sales_data.groupby("State")["Sales"].sum().reset_index()

total_sales_by_state

                   State        Sales
0                Alabama   19510.6400
1                Arizona   35272.6570
2               Arkansas   11678.1300
3             California  446306.4635
4               Colorado   31841.5980
5            Connecticut   13384.3570
6               Delaware   27322.9990
7   District of Columbia    2865.0200
8                Florida   88436.5320
9                Georgia   48219.1100
10                 Idaho    4382.4860
11              Illinois   79236.5170
12               Indiana   48718.4000
13                  Iowa    4443.5600
14                Kansas    2914.3100
15              Kentucky   36458.3900
16             Louisiana    9131.0500
17                 Maine    1270.5300
18              Maryland   23705.5230
19         Massachusetts   28634.4340
20              Michigan   76136.0740
21             Minnesota   29863.1500
22           Mississippi   10771.3400
23              Missouri   22205.1500
24               Montana    5589.3520
25              Nebraska    7464.9300
26                Nevada   16729.1020
27         New Hampshire    7292.5240
28            New Jersey   34610.9720
29            New Mexico    4783.5220
30              New York  306361.1470
31        North Carolina   55165.9640
32          North Dakota     919.9100
33                  Ohio   75130.3500
34              Oklahoma   19683.3900
35                Oregon   17284.4620
36          Pennsylvania  116276.6500
37          Rhode Island   22525.0260
38        South Carolina    8481.7100
39          South Dakota    1315.5600
40             Tennessee   30661.8730
41                 Texas  168572.5322
42                  Utah   11220.0560
43               Vermont    8929.3700
44              Virginia   70636.7200
45            Washington  135206.8500
46         West Virginia    1209.8240
47             Wisconsin   31173.4300
48               Wyoming    1603.1360

In [54]:
total_sales_by_state.sort_values(by="Sales", ascending=False, inplace=True)

total_sales_by_state

                   State        Sales
3             California  446306.4635
30              New York  306361.1470
41                 Texas  168572.5322
45            Washington  135206.8500
36          Pennsylvania  116276.6500
8                Florida   88436.5320
11              Illinois   79236.5170
20              Michigan   76136.0740
33                  Ohio   75130.3500
44              Virginia   70636.7200
31        North Carolina   55165.9640
12               Indiana   48718.4000
9                Georgia   48219.1100
15              Kentucky   36458.3900
1                Arizona   35272.6570
28            New Jersey   34610.9720
4               Colorado   31841.5980
47             Wisconsin   31173.4300
40             Tennessee   30661.8730
21             Minnesota   29863.1500
19         Massachusetts   28634.4340
6               Delaware   27322.9990
18              Maryland   23705.5230
37          Rhode Island   22525.0260
23              Missouri   22205.1500
34              Oklahoma   19683.3900
0                Alabama   19510.6400
35                Oregon   17284.4620
26                Nevada   16729.1020
5            Connecticut   13384.3570
2               Arkansas   11678.1300
42                  Utah   11220.0560
22           Mississippi   10771.3400
16             Louisiana    9131.0500
43               Vermont    8929.3700
38        South Carolina    8481.7100
25              Nebraska    7464.9300
27         New Hampshire    7292.5240
24               Montana    5589.3520
29            New Mexico    4783.5220
13                  Iowa    4443.5600
10                 Idaho    4382.4860
14                Kansas    2914.3100
7   District of Columbia    2865.0200
48               Wyoming    1603.1360
39          South Dakota    1315.5600
17                 Maine    1270.5300
46         West Virginia    1209.8240
32          North Dakota     919.9100

In [55]:
avg_sales_by_state = sales_data.groupby("State")["Sales"].mean().reset_index()

avg_sales_by_state.sort_values(by="Sales", ascending=False, inplace=True)

avg_sales_by_state

                   State        Sales
48               Wyoming  1603.136000
43               Vermont   811.760909
26                Nevada   428.951333
37          Rhode Island   409.545927
24               Montana   372.623467
12               Indiana   360.877037
23              Missouri   336.441667
21             Minnesota   335.541011
0                Alabama   319.846557
44              Virginia   315.342500
46         West Virginia   302.456000
20              Michigan   300.933099
34              Oklahoma   298.233182
47             Wisconsin   296.889810
6               Delaware   293.795688
7   District of Columbia   286.502000
28            New Jersey   283.696492
30              New York   279.271784
9                Georgia   272.424350
27         New Hampshire   270.093481
45            Washington   268.267560
15              Kentucky   266.119635
8                Florida   237.095260
3             California   229.345562
18              Maryland   225.766886
31        North Carolina   223.343984
16             Louisiana   222.708537
19         Massachusetts   212.106919
42                  Utah   211.699170
10                 Idaho   208.689810
22           Mississippi   203.232830
38        South Carolina   201.945476
36          Pennsylvania   199.788058
25              Nebraska   196.445526
2               Arkansas   194.635500
4               Colorado   177.886022
41                 Texas   173.250290
13                  Iowa   170.906154
40             Tennessee   167.551219
33                  Ohio   165.485352
11              Illinois   164.050760
5            Connecticut   163.223866
17                 Maine   158.816250
1                Arizona   158.173350
35                Oregon   141.675918
32          North Dakota   131.415714
29            New Mexico   129.284378
14                Kansas   121.429583
39          South Dakota   109.630000

In [60]:
avg_total_sales = sales_data.groupby("State")["Sales"].agg([np.sum, np.mean, np.max]).reset_index()

avg_total_sales

                   State          sum         mean        max
0                Alabama   19510.6400   319.846557   3040.000
1                Arizona   35272.6570   158.173350   1879.960
2               Arkansas   11678.1300   194.635500   1793.980
3             California  446306.4635   229.345562   8187.650
4               Colorado   31841.5980   177.886022   2549.985
5            Connecticut   13384.3570   163.223866   1133.350
6               Delaware   27322.9990   293.795688  10499.970
7   District of Columbia    2865.0200   286.502000   1379.920
8                Florida   88436.5320   237.095260  22638.480
9                Georgia   48219.1100   272.424350   6354.950
10                 Idaho    4382.4860   208.689810   1128.390
11              Illinois   79236.5170   164.050760   2799.960
12               Indiana   48718.4000   360.877037  17499.950
13                  Iowa    4443.5600   170.906154   1408.100
14                Kansas    2914.3100   121.429583    360.380
15              Kentucky   36458.3900   266.119635   3080.000
16             Louisiana    9131.0500   222.708537   1665.620
17                 Maine    1270.5300   158.816250    437.850
18              Maryland   23705.5230   225.766886   2541.980
19         Massachusetts   28634.4340   212.106919   1737.180
20              Michigan   76136.0740   300.933099   9892.740
21             Minnesota   29863.1500   335.541011   9449.950
22           Mississippi   10771.3400   203.232830   2430.080
23              Missouri   22205.1500   336.441667   4899.930
24               Montana    5589.3520   372.623467   2999.950
25              Nebraska    7464.9300   196.445526   2479.960
26                Nevada   16729.1020   428.951333   4535.976
27         New Hampshire    7292.5240   270.093481   2249.910
28            New Jersey   34610.9720   283.696492   9099.930
29            New Mexico    4783.5220   129.284378    883.840
30              New York  306361.1470   279.271784  11199.968
31        North Carolina   55165.9640   223.343984   7999.980
32          North Dakota     919.9100   131.415714    704.760
33                  Ohio   75130.3500   165.485352   4499.985
34              Oklahoma   19683.3900   298.233182   1805.880
35                Oregon   17284.4620   141.675918   1487.040
36          Pennsylvania  116276.6500   199.788058   8399.976
37          Rhode Island   22525.0260   409.545927   5399.910
38        South Carolina    8481.7100   201.945476   1690.040
39          South Dakota    1315.5600   109.630000    416.320
40             Tennessee   30661.8730   167.551219   2314.116
41                 Texas  168572.5322   173.250290   8159.952
42                  Utah   11220.0560   211.699170   1499.950
43               Vermont    8929.3700   811.760909   4404.900
44              Virginia   70636.7200   315.342500   8749.950
45            Washington  135206.8500   268.267560  13999.960
46         West Virginia    1209.8240   302.456000    673.344
47             Wisconsin   31173.4300   296.889810   2807.840
48               Wyoming    1603.1360  1603.136000   1603.136

In [61]:
sales_data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [63]:
sales_data["Segment"].value_counts()

Segment
Consumer       5101
Corporate      2953
Home Office    1746
Name: count, dtype: int64

In [64]:
avg_sales_by_segment = sales_data.groupby("Segment")["Sales"].mean().reset_index()

avg_sales_by_segment

       Segment       Sales
0     Consumer  225.065777
1    Corporate  233.150720
2  Home Office  243.403309

In [65]:
sales_category_sub = sales_data.groupby(["Category", "Sub-Category"])["Sales"].agg([np.sum, np.mean, np.max])


sales_category_sub

                                      sum         mean        max
Category        Sub-Category
Furniture       Bookcases     113813.1987   503.598224   4404.900
                Chairs        322822.7310   531.833165   4416.174
                Furnishings    89212.0180    95.823865   1336.440
                Tables        202810.6280   645.893720   4297.644
Office Supplies Appliances    104618.4030   227.926804   2625.120
                Art            26705.4100    34.019631   1113.024
                Binders       200028.7850   134.067550   9892.740
                Envelopes      16128.0460    65.032444    604.656
                Fasteners       3001.9600    14.027850     93.360
                Labels         12347.7260    34.587468    786.480
                Paper          76828.3040    57.420257    733.950
                Storage       219343.3920   263.633885   2934.330
                Supplies       46420.3080   252.284283   8187.650
Technology      Accessories   164186.7000   217.178175   3347.370
                Copiers       146248.0940  2215.880212  17499.950
                Machines      189238.6310  1645.553313  22638.480
                Phones        327782.4480   374.180877   4548.810